### ISSUE TITLE
Is it possible to have grid items with variable heights?

### ISSUE THREAD

**Issue by nikolasstow** [SwiftUIExtensions/Grid#19]
I'd like to achieve a layout similar to Google Keep, is something like this possible? [(Screenshot)](https://imgur.com/gallery/G9H1FIg)

**Comment by ay42** [comment]
@nikolasstow unfortunately not right now. But this is something we should definitely do.

**Comment by ay42** [comment]
@nikolasstow This layout is now possible with 0.7.0
<img width="1000" alt="iPad2" src="https://user-images.githubusercontent.com/2933241/69005371-29786100-08d6-11ea-9019-2c2b965a2132.png">
