### ISSUE TITLE
Init with @functionBuilder

### ISSUE THREAD

**Issue by ay42** [SwiftUIExtensions/Grid#2]
Allow users to init Grid with function builder
```swift
Grid {
    Text("Item")
    Text("Item2")
}
```

**Comment by ay42** [comment]
This is related to #8 
If anyone figured out how to do this please let me know.

**Comment by TilBlechschmidt** [comment]
Looks like this could be relevant:
https://developer.apple.com/documentation/swiftui/viewbuilder
Will investigate further.

**Comment by ay42** [comment]
@TilBlechschmidt we were able to init it with function builder in previous release
https://github.com/spacenation/grid/blob/eafea07725c1172fe630d6724bd6edac06bef728/Sources/Grid/Grid.swift#L10-L14
But the difficulty here is to process view builder directly like so:
```swift
public init(@ViewBuilder content: () -> Content) { ? }
```
```swift
Grid {
    Text("1")
}
```

**Comment by hmerzin** [comment]
Hi! I would love to take this issue. Any advice on a good place to start?

**Comment by ay42** [comment]
@hmerzin Hi! This is as far as I have been able to take it
```swift
extension Grid {
    public init<Data: RandomAccessCollection, ID, Item: View>(@ViewBuilder content: () -> Content) where Content == ForEach<Data, ID, Item> {
        let views = content()
        self.items = views.data.map { AnyView(views.content($0)) }
    }
}
```
This allows to init grid like so:
```swift
Grid {
    ForEach(...)
}
```
I honestly have to idea how to achieve the behaviour of native elements like List, Group, HStack.
There it is possible to just do this and it works:
```swift
HStack {
    Text("1")
    Text("2")
}
```
It would be awesome if you can figure this out.

**Comment by hmerzin** [comment]
as luck would have it, I recall reading a blog post a few weeks agothat elaborates on function builders and how one might be able to harness that syntax, though I am not entirely sure if it is possible outside of a SwiftUI context, as I remember seeing a constraint on the syntax that I thought was a bit strange. Nevertheless, I will take a look and let you know what I find and if I can prototype a solution!

thanks,
Harry

**Comment by ay42** [comment]
@hmerzin Looks there is a way to do this (#29). It's not perfect but it's an API we are looking for. Is this something similar to what you wanted to implement? Let me know

**Comment by hmerzin** [comment]
@ay42 using @ViewBuilder was exactly the syntax that I was exploring for implementing this. I think I am pretty close, but basically I have just been fiddling with the initializer for HStack

**Comment by ay42** [comment]
#31 has improvements that address this issue as well.
I feel like we can close this.
